modLoader = 'lowcodefml'
loaderVersion = '[40,)'
license = 'GPL-3.0'
showAsResourcePack = false
mods = [
	{ modId = "small_structures", version = "0.5+1.21.9-26.2+UNIVERSAL", displayName = "Small Structures", description = "Adds small vanilla-like structures", logoFile = "pack.png", updateJSONURL = "https://api.modrinth.com/updates/small-structures/forge_updates.json", displayURL = "https://modrinth.com/datapack/small-structures", authors = "GDLev" }
]